### ISSUE TITLE
Why I got even larger Params?

### ISSUE THREAD

**Issue by preminstrel** [zqu1992/ALQ#1]
I run the command `python lenet5.py --PRETRAIN --ALQ --POSTTRAIN `. 
I got the origin model which is 3,373KB.
However, after quantization, the model is 11,161KB.
Why? Please help me.
Thanks for your time!
Pictures:
![image](https://user-images.githubusercontent.com/60024807/134009257-7f486473-7b84-45b5-b8b5-12e44bed2471.png)

**Comment by zqu1992** [comment]
Hi, thanks for your interest in our work.
The file size of _lenet5_model.pth_ is larger than _lenet5_model_ori.pth_, because we also store multi-bit objects (class defined in `binarynet.py`) in _lenet5_model.pth_. You may see the functions, `save_model` and `save_model_ori` in `train.py`
By the way, the `state_dict()` size of the original network and the ALQ-quantized network are the **same**, since the weights in both networks are represented in floating-point values, although the weights in the ALQ-quantized network are already quantized.

**Comment by preminstrel** [comment]
Thank you! I got it!
I noticed that the functions in `train.py` are, for conv2d, and I wonder that if the method can be applied for conv1d and maxpool1d.
Thank you for your time and Happy mid-Autumn Festival. @zqu1992 😊

**Comment by zqu1992** [comment]
Normal pooling layers are parameter-free, thus, do not need to be quantized.
ALQ should also work for other convolution layers. The most significant difference in comparison to `Conv2d` is the defined `structure` in the multi-bit class. In other words, any code blocks related to `self.structure` in the class definition should be adjusted accordingly, whereas the other blocks may remain the same. You may also see these differences between the class definition of `ConvLayer_bin` and that of `FCLayer_bin`.
Happy mid-Autumn Festival to you too.

**Comment by preminstrel** [comment]
Thanks for your time!
